version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
      - echo copy setting.xml to Local
      - cp /config/settings.xml /root/.m2/settings.xml
    finally:
      - cat /root/.m2/settings.xml
      - Copy finished
  build:
    commands:
      - echo MVN Build is Starting....
      - mvn deploy
    finally:
      - MVN Build Finished
artifacts:
  files:
    - config/settings.xml
cache:
  paths:
    - '/root/.m2/**/*'
